#!/bin/bash

cp ec "/usr/bin"

if [ -d "/usr/share/EC" ]
then
  echo "/usr/share/EC found"
else
  mkdir "/usr/share/EC"
fi

if [ -d "/usr/share/EC/ec" ]
then
  echo "/usr/share/EC/ec found"
else
  mkdir "/usr/share/EC/ec"
fi

cd "share"

cp -r * "/usr/share/EC/ec"
