#include "student.h"

EC_VAR_FUNCTIONS(Student)

EC_ARRAY_FUNCTIONS(Student)

EC_ARRAY_SORT_FUNCTION(Student, no)
EC_ARRAY_SEARCH_WITH_INT_FUNCTION(Student, no)
EC_ARRAY_SEARCH_WITH_STR_FUNCTION(Student, name)
EC_ARRAY_SEARCH_MAX_FUNCTION(Student, no)
EC_ARRAY_SEARCH_MIN_FUNCTION(Student, no)

EC_LIST_FUNCTIONS(Student)
EC_LIST_SORT_FUNCTION(Student, no)

EC_QUEUE_FUNCTIONS(Student)

EC_STACK_FUNCTIONS(Student)

/* Reference */
EC_VAR_REF_FUNCTIONS(Student)
