#include "student.h"

EC_VAR_FUNCTIONS(Student)
EC_ARRAY_FUNCTIONS(Student)

EC_ARRAY_SORT_FUNCTION(Student, no)

EC_ARRAY_REVERSE_FUNCTION(Student)

EC_ARRAY_SEARCH_FUNCTION(Student, no)
EC_ARRAY_SEARCH_MAX_FUNCTION(Student, no)
EC_ARRAY_SEARCH_MIN_FUNCTION(Student, no)
