#ifndef VERSION_H
#define VERSION_H

#ifdef VERSION
#undef VERSION
#define VERSION 1
#endif // VERSION

#ifdef VERSION_YEARS
#undef VERSION_YEARS
#define VERSION_YEARS 0
#endif // VERSION_YEARS

#ifdef VERSION_MONTHS
#undef VERSION_MONTHS
#define VERSION_MONTHS 0
#endif //VERSION_MONTHS

#ifdef VERSION_DAYS
#undef VERSION_DAYS
#define VERSION_DAYS 0
#endif //VERSION_DAYS

#endif // VERSION_H
